name: Update Job Listings

on:
  schedule:
    - cron: '0 0 * * *'  # every 24 hours
  workflow_dispatch:

jobs:
  update-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python daily_scraper.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/jobs.csv model/vectorizer.pkl model/linkage_matrix.pkl
          git commit -m "🕒 Daily job update"
          git push
